import { ColorsAdmin } from "@teslo/interfaces";

export const THEMED_SIDEBAR_CLASSNAMES_BLUE: ColorsAdmin = {
  topLogoContainer: "bg-blue-700 border-blue-600 border-t-0",
  headerTop: "bg-blue-600",
  textColor: "text-gray-50",
  textSubtitleSidebar: "text-gray-50",
  hoverNavToggle: "hover:bg-blue-700",
  sidebarContainer: "bg-blue-700 border-0",
  sidebarItemHover: "hover:bg-blue-600",
  sidebarItemDropdown: "hover:bg-blue-500",
  sidebarDropdownCollapsedContainer: "bg-blue-800",
  loaderColor: "text-blue-700",
  backgroundHome: "bg-blue-800",
  isThemed: true,
  isThemeDarkLogin: true,
  isHeaderTop: true,
  enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_SKY: ColorsAdmin = {
  topLogoContainer: "bg-sky-700 border-sky-600 border-t-0",
  headerTop: "bg-sky-600",
  textColor: "text-gray-50",
  textSubtitleSidebar: "text-gray-50",
  hoverNavToggle: "hover:bg-sky-700",
  sidebarContainer: "bg-sky-700 border-0",
  sidebarItemHover: "hover:bg-sky-600",
  sidebarItemDropdown: "hover:bg-sky-500",
  sidebarDropdownCollapsedContainer: "bg-sky-800",
  loaderColor: "text-sky-700",
  backgroundHome: "bg-sky-800",
  isThemed: true,
  isThemeDarkLogin: true,
  isHeaderTop: true,
  enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_CYAN: ColorsAdmin = {
  topLogoContainer: "bg-cyan-700 border-cyan-600 border-t-0",
  headerTop: "bg-cyan-600",
  textColor: "text-gray-50",
  textSubtitleSidebar: "text-gray-50",
  hoverNavToggle: "hover:bg-cyan-700",
  sidebarContainer: "bg-cyan-700 border-0",
  sidebarItemHover: "hover:bg-cyan-600",
  sidebarItemDropdown: "hover:bg-cyan-500",
  sidebarDropdownCollapsedContainer: "bg-cyan-800",
  loaderColor: "text-cyan-700",
  backgroundHome: "bg-cyan-800",
  isThemed: true,
  isThemeDarkLogin: true,
  isHeaderTop: true,
  enableClothesShopping: true,
};
