import { ColorsAdmin } from "@teslo/interfaces";

export const THEMED_SIDEBAR_CLASSNAMES_BLACK: ColorsAdmin = {
	topLogoContainer: "bg-black border-gray-900 border-t-0",
	headerTop: "bg-neutral-900",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-neutral-700",
	sidebarContainer: "bg-black border-0",
	sidebarItemHover: "hover:bg-neutral-900",
	sidebarItemDropdown: "hover:bg-neutral-800",
	sidebarDropdownCollapsedContainer: "bg-neutral-900",
	loaderColor: "text-black",
	backgroundHome: "bg-black",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_SLATE: ColorsAdmin = {
	topLogoContainer: "bg-slate-900 border-slate-800 border-t-0",
	headerTop: "bg-slate-800",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-slate-700",
	sidebarContainer: "bg-slate-800 border-0",
	sidebarItemHover: "hover:bg-slate-700",
	sidebarItemDropdown: "hover:bg-slate-500",
	sidebarDropdownCollapsedContainer: "bg-slate-700",
	loaderColor: "text-slate-700",
	backgroundHome: "bg-slate-800",
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,

	isThemed: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_GRAY: ColorsAdmin = {
	topLogoContainer: "bg-gray-800 border-gray-700 border-t-0",
	headerTop: "bg-gray-700",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-gray-800",
	sidebarContainer: "bg-gray-700 border-0",
	sidebarItemHover: "hover:bg-gray-800",
	sidebarItemDropdown: "hover:bg-gray-900",
	sidebarDropdownCollapsedContainer: "bg-gray-800",
	loaderColor: "text-gray-700",
	backgroundHome: "bg-gray-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_ZINC: ColorsAdmin = {
	topLogoContainer: "bg-zinc-900 border-zinc-800 border-t-0",
	headerTop: "bg-zinc-800",
	textColor: "text-zinc-50",
	textSubtitleSidebar: "text-zinc-50",
	hoverNavToggle: "hover:bg-zinc-700",
	sidebarContainer: "bg-zinc-800 border-0",
	sidebarItemHover: "hover:bg-zinc-700",
	sidebarItemDropdown: "hover:bg-zinc-500",
	sidebarDropdownCollapsedContainer: "bg-zinc-700",
	loaderColor: "text-zinc-700",
	backgroundHome: "bg-zinc-800",
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,

	isThemed: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_NEUTRAL: ColorsAdmin = {
	topLogoContainer: "bg-neutral-900 border-neutral-800 border-t-0",
	headerTop: "bg-neutral-800",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-neutral-700",
	sidebarContainer: "bg-neutral-800 border-0",
	sidebarItemHover: "hover:bg-neutral-700",
	sidebarItemDropdown: "hover:bg-neutral-500",
	sidebarDropdownCollapsedContainer: "bg-neutral-700",
	loaderColor: "text-neutral-700",
	backgroundHome: "bg-neutral-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_STONE: ColorsAdmin = {
	topLogoContainer: "bg-stone-900 border-stone-800 border-t-0",
	headerTop: "bg-stone-800",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-stone-700",
	sidebarContainer: "bg-stone-800 border-0",
	sidebarItemHover: "hover:bg-stone-700",
	sidebarItemDropdown: "hover:bg-stone-500",
	sidebarDropdownCollapsedContainer: "bg-stone-700",
	loaderColor: "text-stone-700",
	backgroundHome: "bg-stone-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};
