import { ColorsAdmin } from "@teslo/interfaces";

export const THEMED_SIDEBAR_CLASSNAMES_RED: ColorsAdmin = {
	topLogoContainer: "bg-red-800 border-red-600 border-t-0",
	headerTop: "bg-red-600",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-red-700",
	sidebarContainer: "bg-red-700 border-0",
	sidebarItemHover: "hover:bg-red-600",
	sidebarItemDropdown: "hover:bg-red-500",
	sidebarDropdownCollapsedContainer: "bg-red-600",
	loaderColor: "text-red-700",
	backgroundHome: "bg-red-800",

	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_ROSE: ColorsAdmin = {
	topLogoContainer: "bg-rose-800 border-rose-600 border-t-0",
	headerTop: "bg-rose-600",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-rose-700",
	sidebarContainer: "bg-rose-700 border-0",
	sidebarItemHover: "hover:bg-rose-600",
	sidebarItemDropdown: "hover:bg-rose-500",
	sidebarDropdownCollapsedContainer: "bg-rose-600",
	loaderColor: "text-rose-700",
	backgroundHome: "bg-rose-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_ORANGE: ColorsAdmin = {
	topLogoContainer: "bg-orange-700 border-orange-500 border-t-0",
	headerTop: "bg-orange-600",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-orange-700",
	sidebarContainer: "bg-orange-500 border-0",
	sidebarItemHover: "hover:bg-orange-600",
	sidebarItemDropdown: "hover:bg-orange-700",
	sidebarDropdownCollapsedContainer: "bg-orange-600",
	loaderColor: "text-orange-700",
	backgroundHome: "bg-orange-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_YELLOW: ColorsAdmin = {
	topLogoContainer: "bg-yellow-700 border-yellow-500 border-t-0",
	headerTop: "bg-yellow-600",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-yellow-700",
	sidebarContainer: "bg-yellow-500 border-0",
	sidebarItemHover: "hover:bg-yellow-600",
	sidebarItemDropdown: "hover:bg-yellow-700",
	sidebarDropdownCollapsedContainer: "bg-yellow-600",
	loaderColor: "text-yellow-700",
	backgroundHome: "bg-yellow-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};

export const THEMED_SIDEBAR_CLASSNAMES_AMBER: ColorsAdmin = {
	topLogoContainer: "bg-amber-700 border-amber-500 border-t-0",
	headerTop: "bg-amber-600",
	textColor: "text-gray-50",
	textSubtitleSidebar: "text-gray-50",
	hoverNavToggle: "hover:bg-amber-700",
	sidebarContainer: "bg-amber-500 border-0",
	sidebarItemHover: "hover:bg-amber-600",
	sidebarItemDropdown: "hover:bg-amber-700",
	sidebarDropdownCollapsedContainer: "bg-amber-600",
	loaderColor: "text-amber-700",
	backgroundHome: "bg-amber-800",
	isThemed: true,
	isThemeDarkLogin: true,
	isHeaderTop: true,
	enableClothesShopping: true,
};
