version: "3"

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: H5tFSfHUY#$3aM$B
      POSTGRES_DB: MonkeySat
    container_name: monkeysat
    volumes:
      - ./postgres:/var/lib/postgresql/data
